# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'
use_frameworks!

target 'WeekFlex' do
  # Comment the next line if you don't want to use dynamic frameworks
  

  # Pods for WeekFlex
  pod "RxSwift" 
  pod "RxCocoa"
  pod 'Moya', '~> 14.0'
  pod "Alamofire"
  pod 'lottie-ios'
  pod 'KakaoSDKAuth', '2.11.2'
  pod 'KakaoSDKUser', '2.11.2'
  pod 'KakaoSDKCommon', '2.11.2'
  pod 'GoogleSignIn'

end
